- name: Print distribution
  ansible.builtin.debug:
    msg: System {{ ansible_facts['os_family'] }}; Distr {{ ansible_facts['ansible_distribution'] }}
- name: Install golang
  community.general.snap:
    name:
      - go
    classic: true
- name: Install recordgetter
  ansible.builtin.command: go install github.com/brotherlogic/{{ item }}/{{ item }}_cli@latest
  loop:
    - recordgetter
    - recordcleaner
    - recordcollection
