---
- name: Initialize the host machine
  hosts: host
  tasks:
  - name: Add a cron entry to update all machines every week
    ansible.builtin.cron:
      name: "Update Machines"
      minute: "0"
      hour: "2"
      weekday: "0"
      job: "ansible-playbook --vault-password-file=/home/simon/machines/.vault_pass /home/simon/machines/update.yml"
  - name: Add a cron entry to run the install script if the git repo changes
    ansible.builtin.cron:
      name: "Update Machines"
      minute: "*/5"
      job: "/home/simon/machines/run.sh"
  - name: Suppress ansible output
    ansible.builtin.blockinfile:
      path: /home/simon/.ansible.cfg
      block: |
        [defaults]
        inventory  = /home/simon/machines/hosts