- name: Step 1 (sudo apt-get install -y ca-certificates curl)
  apt:
    name: 
    - ca-certificates
    - curl
- name: run GPG
  ansible.builtin.get_url:
    url:  https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/trusted.gpg.d/gcloud.asc
    mode: '0644'
    force: true
- name: Step 4b (sudo apt-get install -y kubectl)
  apt:
    update-cache: yes
    name: kubectl
