- name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
  ansible.builtin.cron:
    name: "run print"
    minute: "*/2"
    job: "go install github.com/brotherlogic/rprinter@latest && rprinter"