- name: Runs updates for all development machines
  hosts: dev
  become: true
  vars_files:
  - secret
  tasks:
    - include: install-kubectl.yml
- name: Setup *all* machines
  hosts: all
  become: true
  vars_files:
  - secret
  tasks:
    - include: install-exporter.yml 