- name: Install apt packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
- name: run GPG
  ansible.builtin.get_url:
    url:  https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /etc/apt/trusted.gpg.d/node.asc
    mode: '0644'
    force: true
- name: install node
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
      - nodejs