- name: Download flux installer
  ansible.builtin.get_url: 
    url: https://fluxcd.io/install.sh 
    dest: /tmp/flux-installer.sh
    
- name: Make exectuable
  file:
    path: /tmp/flux-installer.sh 
    mode: a+x

#- name: Execute the flux-installer.sh
#  shell: /tmp/flux-installer.sh

- name: Remove the flux-installer.sh
  file: 
    path: /tmp/flux-installer.sh 
    state: absent