- name: Install apt packages
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
- name: run GPG
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
      - docker
#      - docker-ce-cli 
#      - containerd.io 
#      - docker-compose-plugin