- name: check if rules file exists
  stat: 
    path: /usr/bin/argon-config
  register: omv_rules

- name: /test
  debug:
    msg: "Found the file"
  when: omv_rules.stat.exists

- name: Download eon installer
  ansible.builtin.get_url: 
    url: https://download.argon40.com/argoneon.sh
    dest: /tmp/eon-installer.sh
  when: omv_rules.stat.exists == false
  
- name: Make exectuable
  file:
    path: /tmp/eon-installer.sh 
    mode: a+x
  when: omv_rules.stat.exists == false

- name: Execute the installer
  shell: /tmp/eon-installer.sh
  args:
    creates: /usr/sbin/omv-engined
  when: omv_rules.stat.exists == false

- name: Remove the installer
  file: 
    path: /tmp/eon-installer.sh 
    state: absent
  when: omv_rules.stat.exists == false

