- name: Runs updates for all dev machines
  hosts: dev
  vars_files:
    - secret
  roles:
    - chrome

- name: Runs post processing hook on all machines
  hosts: all
  vars_files:
    - secret
  vars:
    github_head: "{{ lookup('file', '.git/refs/heads/main') }}"
    current_timestamp: "{{ ansible_date_time.epoch }}"
  roles:
    - golang
    - base
  post_tasks:
    - include: post.yml
