- name: Runs updates for all development machines
  hosts: dev
  become: true
  vars_files:
  - secret
  vars:
    - goversion: 1.20.1
  tasks:
    - include: install-node.yml
#    - include: install-kubectl.yml
    - include: install-flex.yml
    - include: base-install.yml
    - include: install-docker.yml
#    - include: install-gcloud.yml
    - include: install-go.yml
- name: Setup *all* machines
  hosts: all
  become: true
  vars_files:
  - secret
  tasks:
    - include: install-exporter.yml 
- name: Sync *all* machines
  hosts: all
  tasks:
    - include: kube-sync.yml
- name: Setup argon displays
  hosts: argondisplay
  tasks:
    - include: install-argon-display.yml
    - include: prep-kiosk.yml
- name: Run receipt printer specific stuff
  hosts: receiptprinter
  tasks:
    - include: install-receiptprinter.yml
- name: Setup Eon Nas
  hosts: argoneon
  become: true
  tasks:
    - include: install-eon.yml
    - include: install-omv.yml
- name: Setup One 
  hosts: argonone
  become: true
  tasks:
    - include: install-one.yml
  tags:
    - argon
- name: Setup cluster machines
  hosts: cluster
  become: true
  tasks:
    - include: install-cluster.yml
- name: Setup ubuntu machines
  hosts: ubuntu
  become: true
  tasks:
    - include: install-ubuntu.yml
    - include: set-poe-fan-speeds-ubuntu.yml
- name: Setup raspberrypi machines
  hosts: raspberrypi
  become: true
  tasks:
    - include: set-poe-fan-speeds-rpi.yml