- name: Install needed entities
  apt:
    name: 
    - emacs
    - prometheus-node-exporter
    update_cache: yes
- name: Configure exporter to run on port 9110
  ansible.builtin.lineinfile:
    path: /etc/default/prometheus-node-exporter
    regexp: '^ARGS'
    line: ARGS="--web.listen-address=:9110"