- name: check if rules file exists
  stat: 
    path: /usr/sbin/omv-engined
  register: omv_rules

- name: Download eon installer
  when: omv_rules.stat.exists == false
  ansible.builtin.get_url: 
    url: https://download.argon40.com/argoneon.sh
    dest: /tmp/eon-installer.sh
  
- name: Make exectuable
  when: omv_rules.stat.exists == false
  file:
    path: /tmp/eon-installer.sh 
    mode: a+x

- name: Execute the installer
  when: omv_rules.stat.exists == false
  shell: /tmp/eon-installer.sh
  args:
    creates: /usr/sbin/omv-engined

- name: Remove the installer
  when: omv_rules.stat.exists == false
  file: 
    path: /tmp/eon-installer.sh 
    state: absent