- name: Runs updates for all development machines
  hosts: dev
  become: true
  vars_files:
  - secret
  tasks:
    - include: install-kubectl.yml
    - include: install-flex.yml
    - include: base-install.yml
- name: Setup *all* machines
  hosts: all
  become: true
  vars_files:
  - secret
  tasks:
    - include: install-exporter.yml 
- name: Setup local stuff for dev machines
  hosts: dev
  tasks:
    - include: kube-sync.yml