- name: Prep install
  become: true
  apt:
    name: 
    - rpi-chromium-mods
    - unclutter
    - point-rpi
    - lxplug-volumepulse
    update_cache: yes
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/simon/.config/lxsession/LXDE-pi
    state: directory
    mode: '0755'
- name: Creating a file with content
  copy:
   dest: "/home/simon/.config/lxsession/LXDE-pi/autostart"
   content: |
        @lxpanel --profile LXDE-pi
        @pcmanfm --desktop --profile LXDE-pi
        point-rpi
        @xset s noblank
        @xset s off
        @xset -dpms
        @chromium-browser  --disable-gpu --noerrdialogs --enable-features=OverlayScrollbar --disable-infobars --kiosk file:///home/simon/index.html"
