- name: Set temp0
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*poe_fan_temp0.*'
    line: dtparam=poe_fan_temp0=65000
- name: Set temp1
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*poe_fan_temp1.*'
    line: dtparam=poe_fan_temp1=70000
- name: Set temp2
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*poe_fan_temp2.*'
    line: dtparam=poe_fan_temp2=75000
- name: Set temp3
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    regexp: '^.*poe_fan_temp3.*'
    line: dtparam=poe_fan_temp3=80000
  register: yum_update
- name: Reboot if needed
  ansible.builtin.reboot:
  when:
    - yum_update.changed