- name: Print OS
  ansible.builtin.debug:
    var: ansible_facts['os_family']
- name: Install kubectl for Ubuntu servers
  import_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'ubuntu'