# Install ZSH
- name: Install ZSH
  ansible.builtin.apt:
    become: true
    name: "zsh"
    state: present

# Install Git
- name: Install Git
  ansible.builtin.apt:
    become: true
    name: "git"
    state: present

# Ensure oh-my-zsh is present
- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"

- name: Change user shell to zsh
  ansible.builtin.user:
    become: true
    name: "simon"
    shell: /bin/zsh

- name: Set zsh theme to robbyrussel
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^ZSH_THEME'
    line: ZSH_THEME="robbyrussell"

- name: Setup path to include golang
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: path+=('/home/simon/go/bin/')
    create: yes
