# Install ZSH
- name: Install ZSH
  ansible.builtin.apt:
    become: true
    name: "zsh"
    state: present

# Install Git
- name: Install Git
  ansible.builtin.apt:
    name: "git"
    state: present

# Ensure oh-my-zsh is present
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Change user shell to zsh
  ansible.builtin.user:
    name: "simon"
    shell: /bin/zsh

- name: Set zsh theme to robbyrussel
  ansible.builtin.lineinfile:
    path: /home/simon/.zshrc
    regexp: '^ZSH_THEME'
    line: ZSH_THEME="robbyrussell"

- name: Setup path to include golang
  ansible.builtin.lineinfile:
    path: /home/simon/.zshrc
    line: path+=('/home/simon/go/bin/')
    create: yes
